# ========================================
# Docker Compose配置 - 生产环境（GPU版本）
# ========================================
# 用于生产环境部署，包含所有服务的容器化配置
# 包括：PostgreSQL, Redis, RabbitMQ, Backend, Frontend, AI-Processor
#
# 环境变量配置说明：
# - 根目录 .env: 包含shared配置，供docker-compose使用（postgres/redis/rabbitmq）
# - backend/.env: 包含backend特定配置 + shared配置（通过use-env.sh生成）
# - ai-processor/.env: 包含ai-processor特定配置 + shared配置（通过use-env.sh生成）
# - frontend/.env: 包含frontend特定配置 + shared配置（通过use-env.sh生成）
#
# 网络架构：
# - frontend-network: 前端 <-> 后端通信
# - backend-network: 后端 <-> AI处理模块 <-> 数据层通信
# - data-network: 数据层服务（postgres/redis/rabbitmq）内部通信

services:
    # PostgreSQL数据库
    postgres:
        image: postgres:17.6-alpine
        container_name: var-postgres-prod
        restart: always
        env_file:
            - .env # 使用根目录的.env文件（通过scripts/use-env.ps1生成）
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
            LANG: en_US.utf8
            LC_ALL: en_US.utf8
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - ./storage/postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - data-network
            - backend-network
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2G
                reservations:
                    cpus: '0.5'
                    memory: 512M
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    # Redis缓存
    redis:
        image: redis:8.2.1-alpine
        container_name: var-redis-prod
        restart: always
        env_file:
            - .env # 使用根目录的.env文件（通过scripts/use-env.ps1生成）
        command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ./storage/redis-data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 3s
            retries: 5
        networks:
            - data-network
            - backend-network
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G
                reservations:
                    cpus: '0.25'
                    memory: 256M
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    # RabbitMQ消息队列
    rabbitmq:
        image: rabbitmq:4.1.4-management-alpine
        container_name: var-rabbitmq-prod
        restart: always
        env_file:
            - .env # 使用根目录的.env文件（通过scripts/use-env.ps1生成）
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
        ports:
            - "${RABBITMQ_PORT}:5672"
            # 注意：生产环境建议移除管理端口或使用反向代理+认证保护
            # - "15672:15672"
        volumes:
            - ./storage/rabbitmq-data:/var/lib/rabbitmq
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - data-network
            - backend-network
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G
                reservations:
                    cpus: '0.25'
                    memory: 256M
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    # 后端服务
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: var-backend:latest
        container_name: var-backend-prod
        restart: always
        env_file:
            - ./backend/.env # backend模块的环境变量文件（包含shared配置）
        ports:
            - "8080:8080"
        volumes:
            # 共享存储卷,用于存储上传的视频和处理结果
            - ./storage:/app/storage
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
            interval: 30s
            timeout: 3s
            start_period: 60s
            retries: 3
        networks:
            - frontend-network
            - backend-network
        deploy:
            resources:
                limits:
                    cpus: '4'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 1G
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    # AI处理模块（GPU版本）
    ai-processor:
        build:
            context: ./ai-processor
            dockerfile: Dockerfile  # GPU版本Dockerfile
        image: var-ai-processor:latest
        container_name: var-ai-processor-prod
        restart: always
        env_file:
            - ./ai-processor/.env # ai-processor模块的环境变量文件（包含shared配置）
        ports:
            - "5000:5000"
        volumes:
            # 共享存储卷,用于读取视频和写入处理结果
            - ./storage:/app/storage
            # 临时目录（内存文件系统，提高安全性）
            - type: tmpfs
              target: /tmp
              tmpfs:
                  size: 1073741824 # 1GB
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            backend:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
            interval: 30s
            timeout: 3s
            start_period: 90s
            retries: 3
        networks:
            - backend-network
        # ========================================
        # 容器安全加固配置
        # ========================================
        security_opt:
            # 禁止新权限（防止提权攻击）
            - no-new-privileges:true
        cap_drop:
            # 移除所有 Linux capabilities（最小权限原则）
            - ALL
        cap_add:
            # 只添加必需的 capabilities
            - CHOWN # 修改文件所有者（日志目录等）
            - DAC_OVERRIDE # 绕过文件权限检查（必需）
            - SETGID # 设置 GID（切换用户组）
            - SETUID # 设置 UID（切换用户）
        # 只读根文件系统（提高安全性）- 注意：需要确保所有写入都在 volumes 或 tmpfs 中
        # read_only: true  # 如果启用，需要添加更多 tmpfs 挂载点
        # ========================================
        # GPU和资源配置
        # ========================================
        deploy:
            resources:
                limits:
                    cpus: '8'
                    memory: 16G
                reservations:
                    cpus: '2'
                    memory: 4G
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    # 前端服务
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                NUXT_PUBLIC_API_BASE: ""
        image: var-frontend:latest
        container_name: var-frontend-prod
        restart: always
        ports:
            - "8848:8848"
        depends_on:
            backend:
                condition: service_healthy
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8848/",
                ]
            interval: 30s
            timeout: 3s
            start_period: 15s
            retries: 3
        networks:
            - frontend-network
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 128M
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

# ========================================
# 网络配置 - 多层网络隔离
# ========================================
# 网络架构说明：
# - frontend-network: 前端容器与后端容器通信
# - backend-network: 后端容器、AI处理模块与数据层服务通信
# - data-network: 数据层服务（postgres/redis/rabbitmq）内部通信
#
# 优势：
# 1. 前端无法直接访问数据库，提高安全性
# 2. 各层职责分明，网络流量隔离
# 3. 减少攻击面，即使前端被攻破也无法直接访问数据层
networks:
    frontend-network:
        name: var-frontend-network-prod
        driver: bridge
    backend-network:
        name: var-backend-network-prod
        driver: bridge
    data-network:
        name: var-data-network-prod
        driver: bridge
